// Generated by OpenYan LazyAPI

package main

import (
	"database/sql"
	"fmt"
	"github.com/google/uuid"
)


// User represents the User model
type User struct {
	id uuid.UUID `json:"id"`
	first_name string `json:"first_name"`
	
}

// InsertUser inserts a new User into the database
func InsertUser(db *sql.DB, id uuid.UUID, first_name string, ) error {
	query := "INSERT INTO User (id, first_name) VALUES (?, ?)"
	_, err := db.Exec(query, id, first_name, )
	if err != nil {
		return fmt.Errorf("failed to insert User: %w", err)
	}
	return nil
}

